version: '2'
services:
  test-data:
    image: instructure/core
    entrypoint: /usr/bin/tail -f /dev/null
    volumes:
      - /usr/src/app/coverage

  test:
    build: .
    volumes_from:
      - test-data:rw

  transifex:
    # image: instructure/ruby-node-pg:r2.4n6.x
    build: .
    volumes:
    -  ./:/usr/src/app
